### PR TITLE
feat: Get food recommendations based on weather

### LINKED ISSUE #17: Add food recommendations based on weather
We would like to add a feature for recommending food based on the weather at the user's chosen location. 
@Ahmed-Labs @sumana2001

### PR DESCRIPTION
**Pull request by Ahmed-Labs**
Closes #17 

- Scraped [TasteOfHome](https://www.tasteofhome.com) food articles for food recommendations categorized by season (Spring/Sumer/Fall/Winter), using python and BeautifulSoup4. Collected around 50-100 food names for each season.
- Created 'FoodRecommendation' component that takes in the [Weather Code](https://openweathermap.org/weather-conditions) from the main API fetch  and matches it to one of the four seasons.
- Randomly select and display 3 foods from the matched season. As the weather changes, the component re-renders and generates a new set of recommendations.

### CODE REVIEW

**Review by KoichiMin — APPROVED** [review]
LGTM!

**Review by sumana2001 — COMMENTED** [review]
Screenshot 2023-03-21 at 12 21 41 AM

There is a lot of empty space on both sides. Maybe you could display the food items horizontally instead or just use the left over space by extending the box or something else? What do you think? @KoichiMin @Ahmed-Labs @samyukthagopalsamy

**Comment by KoichiMin** [comment]
@sumana2001  Yeah I agree. I think anyone of those options are good alternatives to making it look better. It all depends on what the team prefers.

**Comment by Ahmed-Labs** [comment]
@sumana2001 @KoichiMin | @samyukthagopalsamy and I tried to make the change you suggested by making the food recommendation container wider, but we found that the UI now lacks uniformity since each component has a different width as shown in the screenshot below. Pls let us know what you think and how else we could change it if need be.

Screen Shot 2023-03-20 at 10 00 22 PM

**Comment by KoichiMin** [comment]
I'm terrible at knowing what's aesthetically better so it's hard for me to give an opinion on it but what if you gave it a longer height. Other than that I think everything else is good.

**Pull request merged**
