### PR TITLE
feat: adding a music recommender

### LINKED ISSUE #16: Adding a music recommender
We are up for adding a music recommendation feature according to the user's location's weather, using Spotify API.

### PR DESCRIPTION
**Pull request by Garvit1809**
We created a music audio player where we are using the SPOTIFY API and getting track recommendations and used the Album ID to get tracks in the IFRAME spotify tag.
closes #16

### CODE REVIEW

**Comment by Garvit1809** [comment]
😭

**Comment by Garvit1809** [comment]
You would need the API keys for that

**Comment by sumana2001** [comment]
@swimmingHaribo you should be able to see the songs now

**Review by sumana2001 — CHANGES_REQUESTED** [review]
Please fix conflicts

**Pull request merged**
